# Generated by Django 5.0.2 on 2024-02-24 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_billingaddress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "years_in_business",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("previous_jobs", models.TextField(blank=True)),
                ("spouse", models.CharField(blank=True, max_length=100)),
                ("children", models.CharField(blank=True, max_length=100)),
                ("pets", models.CharField(blank=True, max_length=100)),
                ("hobbies_and_interests", models.TextField(blank=True)),
                ("city_of_residence", models.CharField(blank=True, max_length=100)),
                ("years_in_city", models.PositiveIntegerField(blank=True, null=True)),
                ("burning_desire", models.TextField(blank=True)),
                ("something_no_one_knows", models.TextField(blank=True)),
                ("key_to_success", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
