# Generated by Django 4.1.9 on 2024-02-13 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0005_foldermanager"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(blank=True, max_length=5, null=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("suffix", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gender", models.CharField(max_length=6)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_service_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gst_registered_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gst_identification_number_or_pan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("industry", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "classification",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "requested_speciality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("membership_status", models.CharField(max_length=11)),
                (
                    "RenewalDueDate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Chapter", models.CharField(blank=True, max_length=255, null=True)),
                ("my_business", models.TextField(blank=True, null=True)),
                ("keywords", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
