# Generated by Django 5.0.2 on 2024-02-27 04:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_accountsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountsettings",
            name="alternate_notification_email",
        ),
    ]
