# Generated by Django 5.0.4 on 2024-04-17 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_gallery'),
        ('base', '0006_remove_accountsettings_alternate_notification_email'),
    ]

    operations = [
    ]
