# Generated by Django 4.1.13 on 2024-05-24 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_merge_20240409_1934"),
        ("base", "0007_merge_20240417_0915"),
    ]

    operations = []
