# Generated by Django 4.1.13 on 2024-05-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_citydata_countrydata_gainsprofile_regin_topsprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citydata",
            name="last_updated_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="countrydata",
            name="last_updated_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="regin",
            name="last_updated_date",
            field=models.DateField(auto_now=True),
        ),
    ]
